import './css/pure.base.css'
import './css/pure.button.css'
import './css/pure.forms.css'
import './css/pure.grid.base.css'
import './css/pure.grid.responsive.css'
import './css/pure.menus.css'
import './css/pure.tables.css'
import './css/index.css'
